pipeline {
    agent { label 'AGENT-1' }

    environment {
        PROJECT    = 'expense'
        COMPONENT  = 'backend'
        ACCOUNT_ID = '672911155156'
        REGION     = 'us-east-1'
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
    }

    stages {

        stage('Checkout Code') {
            steps {
                deleteDir()
                checkout scm
            }
        }

        stage('Read Version') {
            steps {
                script {
                    def packageJson = readJSON file: 'backend/package.json'
                    env.APP_VERSION = packageJson.version
                    echo "Application Version is: ${env.APP_VERSION}"
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Docker Build & Push to ECR') {
            steps {
                dir('backend') {

                    withAWS(region: "${REGION}", credentials: 'aws-creds') {

                        sh """
                        aws ecr get-login-password --region ${REGION} | \
                        docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

                        docker build -t ${PROJECT}/${COMPONENT}:${APP_VERSION} .

                        docker tag ${PROJECT}/${COMPONENT}:${APP_VERSION} \
                        ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APP_VERSION}

                        docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${APP_VERSION}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Build SUCCESS ✅'
        }
        failure {
            echo 'Build FAILED ❌'
        }
    }
}
