pipeline {
    agent { label 'AGENT-1' }

    environment {
        PROJECT   = 'expense'
        COMPONENT = 'backend'
        appversion = ''
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
    }

    stages {

        stage('Read Version') {
            steps {
                script {
                    def packageJson = readJSON file: 'backend/package.json'
                    env.appversion = packageJson.version
                    echo "Application Version is: ${env.appversion}"
                }
            }
        }

    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Build SUCCESS ✅'
        }
        failure {
            echo 'Build FAILED ❌'
        }
    }
}
